{
 "title": "Velome",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   { "name": "time_range", "query": "1y" }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Duration total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(work_status[$time_range:])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status by application",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "sum by (application) (work_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent by application",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (application) (sum_over_time(work_status[$time_range:])) * 60",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Duration total by application",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (application) (sum_over_time(work_status[$time_range:]))",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Duration total by application",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "sum by (application) (sum_over_time(work_status[$time_range:])) * 60",
     "legendFormat": "{{application}}"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Duration total by application",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (application) (sum_over_time(work_status{application=\"$application\"}[$time_range:])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status by feature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "sum by (application, feature) (work_status{application=\"$application\"})",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Duration by feature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "(sum_over_time(work_status{application=\"$application\"}[$time_range:])) * 60",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Duration total by feature",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time((work_status{application=\"$application\"})[$time_range:])",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Percent by feature",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time((work_status{application=\"$application\"})[$time_range:]) * 60",
     "legendFormat": "{{feature}}"
    }
   ]
  }
 ]
}